### PR TITLE
REF simpler recipe that bot can update

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by djhoese** [comment]
Thanks @beckermr. As you mentioned on gitter, the Satpy feedstock recipe isn't compatible with new-ish versions of the autotick bot? So there was a backwards incompatible change in the bot?

Is there something I can look at to know whether other packages of mine are incompatible?

After merging this will the autotick bot see the new version from PyPI or should I manually make that PR?

**Comment by djhoese** [comment]
Does conda-smithy handle this conversion?

**Comment by beckermr** [comment]
Right.

1. So the issue here is using jinja2 for the sha256 key. You can check for that I think. 
2. The file extensions being in jinja2 might also be causing issues.
3. the `fn` field is not being updated correctly right now - this is a known issue (https://github.com/regro/cf-scripts/issues/841)
4. The bot will make the version PR as soon as this PR is merged and it runs again. So wait a few hours and then bump me if that does not happen.

**Comment by beckermr** [comment]
Conda-smithy does not handle this conversion. Most recipes don't look like this one in my experience.

**Pull request merged**
