### PR TITLE
Fix recipe

### PR DESCRIPTION
**Pull request by marcelotrevisani**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
Basically, recipes which are ``noarch: python`` cannot have selectors
please see

https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#architecture-independent-packages

**Comment by djhoese** [comment]
> Basically, recipes which are noarch: python cannot have selectors

Ooohhhh ok. I knew that for operating system selectors, but never thought about it for python selectors. Why delete all the testing stuff? Eh I guess it isn't needed. :man_shrugging:

**Comment by djhoese** [comment]
@marcelotrevisani Not sure what happened but the Azure builds failed with a dependency solve failure. Going to try restarting them in the hopes that something magically changes (since they passed here).

**Comment by djhoese** [comment]
@marcelotrevisani My Azure account doesn't seem to be linked properly to my GitHub account so I can't restart this. Could you have a look at the failing jobs on the master branch?

**Pull request merged**
